# Site Settings
title: Build CRUD REST API using CDK Typescript and Python Lambdas with Dynamo DB
author:
  name: Utkal Nayak
  email: nayak.utkal@gmail.com

# Build settings
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme 
